### ISSUE TITLE
Update to i2p 1.9

### ISSUE THREAD

**Issue by dariusaurius** [ypopovych/docker-i2p#1]
Hi, thanks for providing the docker container. I have installed it successfully on my rasbperry, and now I'm wondering how to update the version from 1.5 to 1.9.

I tried to update it manually inside the docker container using the standard installation guide for Ubuntu/Debian: https://geti2p.net/en/download/debian

It was possible do add the repo and use apt update and upgrade to get the latest packages, but unfortunately the version stays the same as nothing has ever happened.

Any suggestion you can think of?

Thanks and regards

**Comment by ypopovych** [comment]
I updated the docker image.

The image doesn't use the Debian package, it uses the java installer (better compatibility with i2p plugins).
