### ISSUE TITLE
Request: Dynamic dockerfile for i2p version

### ISSUE THREAD

**Issue by dariusaurius** [ypopovych/docker-i2p#2]
Hi,

first, I want to thank you for maintaining this repo and providing the docker image for us.

I've wondered, if you can add an environmental variable into the docker image, which can be used to define the version installed in the dockerfile?

I can see that the version is currently manually defined:

```
ENV I2P_VERSION="1.9.0"
ENV I2P_SHASUM="124a1d917dec1f75dc17b5a062704d5abe259b874655c595a9d8f5fd9494eafd  /tmp/i2pinstall.jar" 
```

Wouldn't it be possible to alter this variables within an `docker-compose.yaml` to build a new image?

Regards, Darius

**Comment by ypopovych** [comment]
Hello.

No. It will not help with docker-compose. You will have to rebuild the image with the docker build. That's why they are no ENV variables. The i2p version can be updated with PR on GitHub.  You must update the version string + sha256 hash of the new i2p jar. I will accept it then.
